name: Dependabot

on:
  push:
#  schedule:
#    - cron: "30 13 * * *"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: code de checkout
        uses: actions/checkout@v3
      - name: Mise en cache des dépendances Go
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.1'
      - name: Setup Dependabot
        uses: dependabot/dependabot-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
