name: Lint Workflow

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - name: Actions Checkout
      uses: actions/checkout@v3

    - name: Analyse statique avec Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
       config: "p/default"

    - name: Analyse de Dockerfile avec Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
       dockerfile: Dockerfile

    - name: Analyse Super-lint sur Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      uses: github/super-linter/slim@v5
      env:
        VALIDATE_ALL_CODEBASE: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
