name: Test Workflow

on:
  push:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup de Go avec la version  ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Execution de tests
      run: go test ./...
